baseURL = 'https://asapdiscovery.org'
languageCode = "en-us"
title = "ASAP Discovery Consortium"
theme = "kube"
description = "ASAP uses AI and structure-based approaches to deliever oral antivirals for viruses of pandemic concern which will be globally and equitably accessible"
Paginate = 4
publishDir = "./public"
pygmentsCodefences = true
pygmentsStyle = "colorful"

[Params]
  RSSLink = "/index.xml"
  author = "newpixcom" # add your company name
  github = "https://github.com/asapdiscovery" # add your github profile name
  email = "john.chodera@choderalab.org"

[[menu.main]]
    name = "Concept"
    weight = -40
    url = "https://www.choderalab.org/news/2021/10/26/asap-avidd-proposal"
[[menu.main]]
    name = "Members"
    weight = -30
    url = "/members/"
[[menu.main]]
    name = "FAQ"
    weight = -20
    url = "/faq/"
[[menu.main]]
    name = "Awards"
    weight = -15
    url = "/awards/"
[[menu.main]]
    name = "Jobs"
    weight = -10
    url = "/jobs/"
[[menu.main]]
    name = "Open Science Forum"
    weight = -5
    url = "/forum/"
[[menu.main]]
    name = "COVID Moonshot"
    weight = 0
    url = "https://postera.ai/moonshot/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
