baseURL = 'https://asapdiscovery.org'
languageCode = "en-us"
title = "ASAP Discovery Consortium"
theme = "kube"
description = "ASAP uses AI and structure-based approaches to deliever oral antivirals for viruses of pandemic concern which will be globally and equitably accessible"
publishDir = "./public"
pygmentsCodefences = true
pygmentsStyle = "colorful"

# Generate robots.txt
enableRobotsTXT = "true"
# ignore files on build:
ignoreFiles = ['data/outputs/preTEPS/']

[Params]
  RSSLink = "/index.xml"
  author = "newpixcom" # add your company name
  github = "https://github.com/asapdiscovery" # add your github profile name
  email = "john.chodera@choderalab.org"

[pagination]
pagination.pagerSize = 4

[[menu.main]]
    name = "Pipeline"
    weight = -50
    url = "/pipeline/"
    identifier = "pipeline"
[[menu.main]]
    name = "Outputs"
    weight = -45
    url = "/outputs/"
    identifier = "outputs"
[[menu.main]]
    name = "Concept"
    weight = -40
    url = "https://www.choderalab.org/news/2021/10/26/asap-avidd-proposal"
    identifier = "concept"
[[menu.main]]
    name = "Members"
    weight = -30
    url = "/members/"
    identifier = "members"
[[menu.main]]
    name = "SAB"
    weight = -25
    url = "/sab/"
    identifier = "sab"
[[menu.main]]
    name = "FAQ"
    weight = -20
    url = "/faq/"
    identifier = "FAQ"
[[menu.main]]
    name = "Awards"
    weight = -15
    url = "/awards/"
    identifier = "awards"
#[[menu.main]]
#    name = "Jobs"
#    weight = -10
#    url = "/jobs/"
#    identifier = "jobs"
[[menu.main]]
    name = "Open Science Forum"
    weight = -5
    url = "/forum/"
    identifier = "forum"
[[menu.main]]
    name = "Open Science"
    weight = 0
    url = "/open-science/"
    identifier = "open-science"
[[menu.main]]
    name = "COVID Moonshot"
    weight = -2
    url = "https://postera.ai/moonshot/"
    identifier = "moonshot"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

