#!/usr/bin/env python3
"""Regenerate data/outputs/protocols.yaml from a protocols.io CSV export.

The published YAML is not a straight rendering of the export: category, target and
cores are ASAP taxonomy that protocols.io does not hold, and some author names need
normalising. Both live alongside this script (taxonomy.yaml, author-aliases.yaml) so a
refresh never loses them.

    python3 protocols-export/convert.py            # rewrite the YAML
    python3 protocols-export/convert.py --dry-run  # report only

Protocols whose taxonomy is still blank are left out of the site and listed at the end
of the run; fill them in in taxonomy.yaml and re-run to publish them.
"""

import argparse
import csv
import re
import sys
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent
REPO = HERE.parent
PROTOCOLS_YAML = REPO / "data" / "outputs" / "protocols.yaml"
TAXONOMY = HERE / "taxonomy.yaml"
ALIASES = HERE / "author-aliases.yaml"
EXPORTS = HERE / "exports"

MAX_AUTHORS = 7
MAX_VERSIONS = 5
DESCRIPTION_LIMIT = 300

HEADER = """# Unified protocols database for ASAP Discovery
# All protocols with consistent tags for filtering
#
# Generated by protocols-export/convert.py -- do not hand-edit.
# Taxonomy (category/target/cores) lives in protocols-export/taxonomy.yaml.
# Author name corrections live in protocols-export/author-aliases.yaml.
"""

# Order of the category sections in the generated file.
UNASSIGNED = "Unassigned"

CATEGORY_ORDER = [
    "Biochemical Assay",
    "Crystallization",
    "Protein Production",
    "Biophysical Assay",
    "ADMET",
    "Antiviral Assay",
    UNASSIGNED,
]

TAXONOMY_FIELDS = ("category", "target", "cores")


def base_url(url):
    """Strip a trailing /vN so a protocol is identified across version bumps."""
    return re.sub(r"/v\d+$", "", url.strip().rstrip("/"))


def latest_version(row):
    """Highest version number the export actually published."""
    latest = 0
    for i in range(1, MAX_VERSIONS + 1):
        if row.get(f"version_{i}_published_on", "").strip():
            latest = i
    return latest


def authors_of(row, aliases):
    """Ordered, de-duplicated author list with name corrections applied.

    creator_name is deliberately ignored: it is the protocols.io account that owns
    the record, which is often the person who ran the export rather than an author.
    """
    names = []
    for i in range(1, MAX_AUTHORS + 1):
        name = row.get(f"author_name_{i}", "").strip()
        if not name:
            continue
        name = aliases.get(name, name)
        if name not in names:
            names.append(name)
    return names


def description_of(row):
    """Newlines become spaces (runs are kept), then truncate with an ellipsis."""
    text = row["description_text"].replace("\r\n", " ").replace("\r", " ")
    text = text.replace("\n", " ").strip()
    if len(text) > DESCRIPTION_LIMIT:
        return text[: DESCRIPTION_LIMIT - 3] + "..."
    return text


def parse_export(path, aliases):
    """CSV rows -> {base url: protocol fields}, minus taxonomy."""
    protocols = {}
    with path.open(newline="", encoding="utf-8") as handle:
        for row in csv.DictReader(handle):
            version = latest_version(row)
            if not version:
                continue
            key = base_url(row["url"])
            protocols[key] = {
                "name": row[f"version_{version}_title"].strip(),
                "url": f"{key}/v{version}",
                "author": "",
                "authors": authors_of(row, aliases),
                "date": row[f"version_{version}_published_on"].strip()[:10],
                "version": f"v{version}",
                "description": description_of(row),
            }
    return protocols


def seed_taxonomy(existing):
    """Build the taxonomy map from the YAML that is already published."""
    return {
        base_url(entry["url"]): {field: entry[field] for field in TAXONOMY_FIELDS}
        for entry in existing
    }


def dump_scalar(value):
    """Render one scalar, quoting only when YAML requires it.

    PyYAML reaches for single quotes; the file uses double, so re-dump those to keep
    regenerated output diff-clean against what is already committed.
    """
    out = yaml.safe_dump(
        {"k": value}, default_flow_style=False, allow_unicode=True, width=10**9
    ).split("k:", 1)[1].strip()
    if out.startswith("'"):
        return dump_quoted(value)
    return out


def dump_quoted(value):
    """Render a scalar in double-quoted style, matching the descriptions in the file."""
    return yaml.safe_dump(
        value, default_style='"', allow_unicode=True, width=10**9
    ).strip()


def dump_list(values, quote=False):
    if quote:
        return "[" + ", ".join("'" + v.replace("'", "''") + "'" for v in values) + "]"
    return yaml.safe_dump(
        values, default_flow_style=True, allow_unicode=True, width=10**9
    ).strip()


def render(entry):
    lines = [
        f"- name: {dump_scalar(entry['name'])}",
        f"  url: {entry['url']}",
        f"  category: {dump_scalar(entry['category'])}",
        f"  target: {dump_scalar(entry['target'])}",
        f"  author: {dump_scalar(entry['author'])}",
        f"  authors: {dump_list(entry['authors'])}",
        f"  date: {entry['date']}",
        f"  version: {entry['version']}",
        f"  description: {dump_quoted(entry['description'])}",
        f"  cores: {dump_list(entry['cores'], quote=True)}",
    ]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--export", type=Path, help="CSV to use (default: newest)")
    parser.add_argument("--dry-run", action="store_true", help="report, do not write")
    args = parser.parse_args()

    export = args.export
    if export is None:
        candidates = sorted(EXPORTS.glob("*.csv"))
        if not candidates:
            sys.exit(f"no CSV export found in {EXPORTS}")
        export = candidates[-1]
    print(f"export:   {export.relative_to(REPO)}")

    aliases = yaml.safe_load(ALIASES.read_text()) if ALIASES.exists() else {}
    existing = yaml.safe_load(PROTOCOLS_YAML.read_text())
    existing_by_url = {base_url(e["url"]): e for e in existing}

    taxonomy = seed_taxonomy(existing)
    if TAXONOMY.exists():
        taxonomy.update(
            {k: v for k, v in (yaml.safe_load(TAXONOMY.read_text()) or {}).items()}
        )

    parsed = parse_export(export, aliases)
    print(f"protocols in export: {len(parsed)}   currently published: {len(existing)}")

    # protocols.io holds several records for some protocols. Those are marked
    # `duplicate_of` in the taxonomy and skipped, so each protocol appears once.
    # Anything else the taxonomy does not cover is published labelled UNASSIGNED,
    # rather than guessed at or hidden.
    needs_taxonomy = []
    duplicates = []
    for key in parsed:
        entry = taxonomy.setdefault(key, {"category": "", "target": "", "cores": []})
        if entry.get("duplicate_of"):
            duplicates.append(key)
        elif not entry.get("category") or not entry.get("target") or not entry.get("cores"):
            needs_taxonomy.append(key)

    if not args.dry_run:
        TAXONOMY.write_text(
            "# ASAP taxonomy for each protocol, keyed on its protocols.io URL.\n"
            "# Fill in blank entries to publish that protocol.\n"
            "# `duplicate_of` marks a protocols.io record that repeats another one; those are\n"
            "# skipped rather than published, so the table shows each protocol once.\n\n"
            + yaml.safe_dump(taxonomy, default_flow_style=False, allow_unicode=True,
                             sort_keys=True, width=10**9)
        )

    # Publish everything bar the duplicates; anything the taxonomy does not cover is
    # labelled rather than inferred, so a gap is visible instead of silently invented.
    publishable = {k: v for k, v in parsed.items() if k not in set(duplicates)}
    for key, entry in publishable.items():
        tags = taxonomy[key]
        entry["category"] = tags.get("category") or UNASSIGNED
        entry["target"] = tags.get("target") or UNASSIGNED
        entry["cores"] = tags.get("cores") or [UNASSIGNED]
        entry["author"] = entry["authors"][0] if entry["authors"] else UNASSIGNED

    # Keep existing entries in their current position; append new ones per category.
    order = {key: i for i, key in enumerate(existing_by_url)}
    sections = []
    for category in CATEGORY_ORDER:
        rows = [e for k, e in publishable.items() if e["category"] == category]
        rows.sort(key=lambda e: order.get(base_url(e["url"]), len(order)))
        if rows:
            sections.append((category, rows))
    leftover = sorted({e["category"] for e in publishable.values()} - set(CATEGORY_ORDER))
    for category in leftover:
        sections.append(
            (category, [e for e in publishable.values() if e["category"] == category])
        )

    out = [HEADER]
    for category, rows in sections:
        out.append(f"\n# {category} Protocols\n")
        out.append("\n\n".join(render(e) for e in rows) + "\n")
    text = "".join(out)

    if args.dry_run:
        print("\n(dry run -- nothing written)")
    else:
        PROTOCOLS_YAML.write_text(text)
        print(f"wrote:    {PROTOCOLS_YAML.relative_to(REPO)}")

    # Report.
    added = [k for k in publishable if k not in existing_by_url]
    removed = [k for k in existing_by_url if k not in parsed]
    changed = []
    for key, entry in publishable.items():
        old = existing_by_url.get(key)
        if old and any(
            str(old.get(f)) != str(entry.get(f)) for f in ("name", "url", "version", "date")
        ):
            changed.append((key, old, entry))

    print(f"\npublished: {len(publishable)}   new: {len(added)}   "
          f"version/date changed: {len(changed)}   gone from export: {len(removed)}   "
          f"skipped as duplicates: {len(duplicates)}")

    if changed:
        print("\nprotocols whose version or date moved:")
        for _, old, new in changed:
            print(f"  {new['name'][:58]}")
            print(f"      {old['version']} {old['date']}  ->  {new['version']} {new['date']}")
    if removed:
        print("\nno longer in the export (kept out of the new file):")
        for key in removed:
            print(f"  {existing_by_url[key]['name'][:70]}")
    if needs_taxonomy:
        print(f"\n{len(needs_taxonomy)} protocol(s) published as '{UNASSIGNED}'. Fill in "
              f"category/target/cores in {TAXONOMY.relative_to(REPO)} to label them:")
        for key in needs_taxonomy:
            print(f"  {parsed[key]['name'][:70]}")
            print(f"      {key}")


if __name__ == "__main__":
    main()
